@startuml

left to right direction

rectangle Book-Application {

usecase UC0 as "US0: Admin Login"
usecase UC1 as "US1: Register new User"
usecase UC2 as "US2: User Login"
usecase UC3 as "US3: Add book to Bookshelf"
usecase UC4 as "US4: View Bookshelf"
usecase UC5 as "US5: Write Review"
usecase UC6 as "US6: View all Bookshelves"
usecase UC7 as "US7: Edit Library"
usecase UC8 as "US8: View Library"

UC0 -- UC6
UC0 -- UC7
UC4 --> UC5
UC8 --> UC3

}
actor "User" as u
u -- UC1
u -- UC2
u -- UC4
u -- UC8


actor "Admin" as a
a -- UC0





@enduml